services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: NjGrrq87BmFCFUcVNN5f4feEBYNGO8bFHjd53JaWHM7zpfLCgQrhwZ30HJh3Sdco+HblSskWMHpLkudFJ2iy3WcjEIXfMu01fAGlzmGvt8bYQNgvbIwmy3iL7Fa4LISpXPfWXEQJ4XSviIfpH4RiavwnQgzBYLC0cp7gLqiY33/u8nGiDhk92A78rpj5p4HEpiyfbN6IYwxrgGNOA+tz3zfCvGl3O7DpfLVJgQFRz5zXXOuywSBx/TdrdqnAnLpdAqXi0ON8/X2QqQ6q3g2KR7ATyrJOepFjbWAPDjDU7Q48eTVcvmJjDIiKLm7HHANNs6cz2Mk50kNGnZf678U+Xd40goQytqlIb8MORNajSLi5WYO2nb2KaePnrGjXqY+AL1bXHTyDFoC+lnn2tbZ/krdBsLXHRWRlQIgBvNY12dyih2WERdchWbhr5VlU3zl8RfwklB/45RjmdbX5EgZaZsT8PXfRLu63O47irzUmFhsDURoOQAOB+u/voitzvTs1c+Hi97IBrANlVMAezOX4ZZheY2BriOHlBFaro6FyqJ2F/yzXV0JuW785ggf1h2at7rGIbJ62ey/B+bdg+4nYENPDtz8KICltZ6ISRpC14Vsh/w3MgJdTl+GIzHF7zimtalQjHj4m+P+ZQdno77bg8WhAsVYKWl+YNQGf+8ms/Jc=
  - secure: fjjt5rLbhMMTdiemL25UQk0HbhVD8i6WjQOzIgjbsCKfkgOL18AieFjYYe4LdwOKTrJ/lEsDJpJkO1B4X2eoYdDBChGjcWYoI4JJ+IWZ7hOqDBh7SVn1c+LBudy2PyghHK43aPxnGHKI7T0pcbDOia/08YcfBm9TifGUZgpQsiV51XGS16OWefr9nSAGSE6uB5sitoh5vaSCkwbXpOBDLKAdL9+xYoCXTB4kQEaW9csOUCvbUimIrMXS8jkb8LwfUZuw/uS9b4AO0TMu6wKUw+l1Qp8hJQlTasAAuvex39MFoT/5BKXEb+rAVGMadhTqlrFrmLBsFyLZo1xxBWgnArj+oEOCDioD2Hu4WmsuYnsqOqVTpvl4Yrjsz5XH29LoVQygOmPubjotNFZLz1I/m0xa7I2HP+jskW8cLAzjD1DXXynzga9Jna4tyXWs6lxSBJVIT9tndS4VL9vQIJvPFnIwYpoHLdOn7Slepvx8Tf3DFUrJnCTeIRRdzNeC0z4h3gaKsP2LL+0luI9BVbqP3JqLW8ToasZQsFZNW7DyVtENnbNBk3M+8FD2NCJlZ85dlVqtz9Y3EZALnjysEo6l9bTV0ZQkthMx9V2R/8qDvxJw9ime3s3hIPouTzigVaGeAL7joRbujnNo6SOFl0/2rrC5Ft7UGzyBdGxGFEKEcdU=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
