services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: Hl14ixZSSoGoJSEdTf4xWGT5vyleEX4fuee7QOMLTKJssi5mXzO9V+OFpt2bTzSsZWdEuKoYZ9Gj2cbhKhZJQCda2L5511Z7bKmM/Q1lW7nNGJTbMPToozqGiARRzK9uEsO/S2hc9MxI6YVnNwR5ciFZXlx3PeOa8tQ6gG56k9ES46rmtW0S1XI7HODOyXjCi0UIsoHkAGqG+1xmJVkD3oFy3QMTWgDAcYv6pYAB8Y/tMT5wIajto3VPMwaDpJjBckJpDpMb3HWhkXcNWopCTVEY5a7Y6mvlutzBpk5sUplnbLBQ0NvpRHDxezzePTM6m3WajsqZBAGR07shSTcqqm2Wv1C96Mv8imrpgZk96iZ7RAQynLqOEuycamCetpan9R1iGC4A9Ae66nCv9GFNBDsdJiYQ2DhLll8n64GgeU/GjU6RJKy005OuF1SiZHNFt+1eUOpC4fHUo0jxmSMwQV/Bn/m2K+q+RLGpyDRJrdLZLijvWB01a73dIGrXiKbyF9b6AqqgcLqG3oSoKm8i0avazzoVgpfWed4HEzPNwWRcLgLvxRjsp39miPCVb3znSObYg6O26RGJRA0s2NwX/aDe10/TZKnW0bNa7z1KlNyufHBt/yTXb8QvXemiodgZPpLguweD3RiWEnkZDAIj4IeZ0mn5OfiloD9niYHF+uk=
  - secure: WV8PHEbXPn6mu5I83/S2rYoe9vwtwBQ+auED5slndatWV1O8PH1oFxCmknAD7jmSbzdZjSObKY59WUa/9VtULlJ+A4/HvTwiHAtwJgRlbAzvjW6/MZlb6xViS97BjLrC7XAlBrwgq9RfoqrbrFCYwHu4Junjmsto14Qp8NvYy/nd8gxsbHjykU0nybnbW7+oTJ1+Xa4YDzl+0qrP9cxFMZfIyWqJondQTO39Iood9ENhMVbKp3hK/FXqJG3VAfZAiZrRbQ9N+VkyxvTCUAU9m59bdxSo4xGe+Qzr73h48UBvwauabE0KduqjovhaejKxj513E7gNR+XNbQjWlEArJY6l4jui+OfSO8QeOnqxrRhQiH10JDKkpAAVjRQiz8MJAW4EFJWZgiH+lF1xuYQQMGBFmgZBGvP9o6vH3yXbblbPSQu/k+8dauoN9tMwO54ImjvyKAsq5vJeHVcSR+WHH3zrBRrbEKDOmzF1AZjex0Z5TJSL3YA+WAWvWAhn4kagszI8UXNCRURmdBRvuh19gxSxfCw5CmM10PFj8Ys2JzEN7PbpzDYzxM2+0Pmpzt2S2YpZhQcqEKjXM23k8DWl7EzFxN6+YvxwviNu4m16Tmaw2wA0FD86S+yJybBqHmJA4T+ZtaWYuMQcx0h0+NjhRGyYQNbhItpVfn8izp1jcwM=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- PYTHONUNBUFFERED=TRUE nb push
