services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: cXrBy0/l/PzMMzqe83+xdHEcbdJ57OVU9qdTa+xv/mgZYfV4vr06JONUVICrvjFYn0c/n6fBhEZBKuP+vNEYxJelZ6Tf4j+/zakeLSl63uWpCZF1mXLAYNNMFa/TmDBJNey6nvw67BGnxr9LKIhxMeXl99ExVrinez96/wlsPZrVQzzxYrikAE55uRZ/mqItiNKkJ9B5Hqi5mcX4tFmnlPDnh56tT4rI/3MOJhdhjhEzrwkl6saAWXHw9ZkLdgO1gLfbsKKZOH/23Ogakb5IvnpJ/YSIfUju+GTN8Rlcu17JTzCn9W/wjroI6SZYi+bJQGh7KMjnQjENMIuiO/h/l96Gu8yNU0XRwqwVmgMiSDc3/04rCK3tfJCHBPk2bSBwI3k8Rz5Ig+mAVY5SoDVSZsXh6rMHiXY4QlnJfnshtxUA0kO4jqeGgnu/n+gzLXimCzwi209oJOcyHo3RPYab4UUB3bC0FiPQ4aylWnXyl37v1DZ39eVgi+/3Z+18QIA+oApIuze1PreyRf7q+TfdxauTVA9tbIBXha3rExwP60FVgK0lT0lIYXJxuhqbBOXMAcWDrCcYyj1VaLmXXKEBQ9qsYbUdIfW3YskMb22CMkzvzKDRPmRy89a5txfAxtxWlzLJeLGejHgelKoxYp+F/irm9Puy4hW0LJLsEUMRhfw=
  - secure: LQwmQ3Uvx5c2bo27gY01fkn27uO0COFBZljkeafv7bv9nTKgK2mY5XiX78TGXGaypfyFuKezmFTLbLO4IMGEIeWrKTQN+8CqMy/55l67FKOm0ylh6Vsy7s1/0LCl5bxlABrbpGlHRJCQC0W+VaK4D+58gDnaN02xEApz1KTJabXYC6Ln3tFl1W56wv7WiTKK/9asHL4AZs37lqV0nGy92qsvO7fDkKwNrUAsyZnlu5QtE9+qwMrtba0aUOJACpHoGmGSDgQc3KsEpqfGpBLtqwR/nOhOmqHMCEbavyi4mSkYHweLIZYiY3xyZWdlWycojHV82gl7q46afxnVBpLXqLOYw7d1BvtiUD0xcDrkr/1o1gpSlLpzONMjrE3C7qHVxobPi1YgXW3xbznzXD0EimV202kGXGGkbwMuwL2KoilYzqJSvR0VxD2EOamYh0TqmMWcd4xXunDoOY4KHnbrvFuKInYHRzqWWuGmkYb0Gl+25DkqS1fUNaKRKKb9MhfJ/eBkXmjUZI6O3/HLZcQskB1dQxlli4xBum8aLUC94lsPavgAxienG1gNItJ14Mzn340zFL4r24SJbNLXqaOs3ZbWvShhZWnspJRKY23AaV6AL6cMAQsUlZKnI368xOwSISi7w2OKn6/xE35CizJLn+zz4GCFHTraU+tuUlCtBgQ=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
