#!/bin/bash

cp /usr/local/etc/php/php.ini-${ENVIRONMENT} /usr/local/etc/php/php.ini
cp /usr/local/etc/php-fpm.d/www.conf-${ENVIRONMENT} /usr/local/etc/php-fpm.d/www.conf

#Enable xdebug
 if [[ ${ENABLE_XDEBUG} == "1" ]] ; then

	sed -i "s|{{REMOTE_HOST}}|${REMOTE_HOST:-localhost}|" /usr/local/etc/php/docker-php-ext-xdebug.ini
	cp /usr/local/etc/php/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    docker-php-ext-enable xdebug

 fi


/usr/local/sbin/php-fpm --force-stderr --nodaemonize -c /usr/local/etc/php/php.ini --fpm-config /usr/local/etc/php-fpm.conf