#!/bin/bash

cp /usr/local/etc/php/php.ini-${ENVIRONMENT} /usr/local/etc/php/php.ini
cp /usr/local/etc/php-fpm.d/www.conf-${ENVIRONMENT} /usr/local/etc/php-fpm.d/www.conf

#Enable xdebug
XdebugFile='/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'

if [[ ${ENABLE_XDEBUG} == "1" ]] ; then
  if [ -f $XdebugFile ]; then
  	echo "Xdebug enabled"
  else
  	echo "Enabling xdebug"

    docker-php-ext-enable xdebug

    if [ -f $XdebugFile ]; then
        if grep -q xdebug.remote_enable "$XdebugFile"; then
            echo "Xdebug already enabled... skipping"
        else
            echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > $XdebugFile
            echo "xdebug.remote_enable=1 "  >> $XdebugFile
            echo "xdebug.remote_log=/tmp/xdebug.log"  >> $XdebugFile
            echo "xdebug.remote_autostart=false "  >> $XdebugFile
            echo "xdebug.remote_host=${REMOTE_HOST:-localhost}" >> $XdebugFile
        fi
    fi
  fi
else
    if [ -f $XdebugFile ]; then
        echo "Disabling Xdebug"
      rm $XdebugFile
    fi
fi


/usr/local/sbin/php-fpm --force-stderr --nodaemonize -c /usr/local/etc/php/php.ini --fpm-config /usr/local/etc/php-fpm.conf